{
    "response": {
        "metadata": {
            "frame_id": "test_throw_catch",
            "frame_name": "test_throw_catch",
            "filename": "test_normal_exceptions.py",
            "defined_lineno": 37
        },
        "identifiers": [
            "b",
            "a",
            "e"
        ],
        "loops": [],
        "events": [
            {
                "lineno": 39,
                "index": 0,
                "offset": 14,
                "filename": "test_normal_exceptions.py",
                "id": "test_throw_catch:0",
                "target": "b",
                "value": "{}",
                "repr": "TypeError('B')",
                "type": "Binding"
            },
            {
                "lineno": 42,
                "index": 1,
                "offset": 26,
                "filename": "test_normal_exceptions.py",
                "id": "test_throw_catch:1",
                "target": "a",
                "value": "{}",
                "repr": "RuntimeError('A')",
                "type": "Binding"
            },
            {
                "lineno": 45,
                "index": 2,
                "offset": 90,
                "filename": "test_normal_exceptions.py",
                "id": "test_throw_catch:2",
                "target": "e",
                "value": "{}",
                "repr": "RuntimeError('A')",
                "type": "Binding"
            },
            {
                "lineno": 47,
                "index": 3,
                "offset": 98,
                "filename": "test_normal_exceptions.py",
                "id": "test_throw_catch:3",
                "target": "b",
                "value": "{}",
                "repr": "RuntimeError('A')",
                "type": "Binding"
            },
            {
                "lineno": 47,
                "index": 4,
                "offset": 106,
                "filename": "test_normal_exceptions.py",
                "id": "test_throw_catch:4",
                "target": "e",
                "value": "null",
                "repr": "None",
                "type": "Binding"
            },
            {
                "lineno": 47,
                "index": 5,
                "offset": 108,
                "filename": "test_normal_exceptions.py",
                "id": "test_throw_catch:5",
                "target": "e",
                "type": "Deletion"
            },
            {
                "lineno": 49,
                "index": 6,
                "offset": 126,
                "filename": "test_normal_exceptions.py",
                "id": "test_throw_catch:6",
                "target": "b",
                "type": "Deletion"
            }
        ],
        "tracingResult": {
            "test_throw_catch:3": [
                "test_throw_catch:2"
            ]
        }
    },
    "tracer.events": [
        {
            "lineno": 39,
            "index": 0,
            "offset": 14,
            "filename": "test_normal_exceptions.py",
            "id": "test_throw_catch:0",
            "target": {
                "name": "b",
                "snapshot": null
            },
            "value": "{}",
            "repr": "TypeError('B')",
            "sources": [],
            "__class__": "Binding"
        },
        {
            "lineno": 42,
            "index": 1,
            "offset": 26,
            "filename": "test_normal_exceptions.py",
            "id": "test_throw_catch:1",
            "target": {
                "name": "a",
                "snapshot": null
            },
            "value": "{}",
            "repr": "RuntimeError('A')",
            "sources": [],
            "__class__": "Binding"
        },
        {
            "lineno": 45,
            "index": 2,
            "offset": 90,
            "filename": "test_normal_exceptions.py",
            "id": "test_throw_catch:2",
            "target": {
                "name": "e",
                "snapshot": null
            },
            "value": "{}",
            "repr": "RuntimeError('A')",
            "sources": [],
            "__class__": "Binding"
        },
        {
            "lineno": 47,
            "index": 3,
            "offset": 98,
            "filename": "test_normal_exceptions.py",
            "id": "test_throw_catch:3",
            "target": {
                "name": "b",
                "snapshot": null
            },
            "value": "{}",
            "repr": "RuntimeError('A')",
            "sources": [
                {
                    "name": "e",
                    "snapshot": {
                        "location": null,
                        "events_pointer": {
                            "b": 0,
                            "a": 0,
                            "e": 0
                        }
                    }
                }
            ],
            "__class__": "Binding"
        },
        {
            "lineno": 47,
            "index": 4,
            "offset": 106,
            "filename": "test_normal_exceptions.py",
            "id": "test_throw_catch:4",
            "target": {
                "name": "e",
                "snapshot": null
            },
            "value": "null",
            "repr": "None",
            "sources": [],
            "__class__": "Binding"
        },
        {
            "lineno": 47,
            "index": 5,
            "offset": 108,
            "filename": "test_normal_exceptions.py",
            "id": "test_throw_catch:5",
            "target": {
                "name": "e",
                "snapshot": null
            },
            "__class__": "Deletion"
        },
        {
            "lineno": 49,
            "index": 6,
            "offset": 126,
            "filename": "test_normal_exceptions.py",
            "id": "test_throw_catch:6",
            "target": {
                "name": "b",
                "snapshot": null
            },
            "__class__": "Deletion"
        }
    ]
}